<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.30.4--0002-develop" />
        <PackageReference Include="CK.Ng.Cris.AspNet.Auth" Version="0.54.2" />
        <PackageReference Include="CK.Ng.UserProfile.NamedUser" Version="0.5.3--0002-develop" />
        <PackageReference Include="CK.Ng.UserProfile.PreferredCulture" Version="0.5.3--0002-develop" />
        <PackageReference Include="CK.Ng.UserProfile.UserPassword" Version="0.5.3--0002-develop" />
        <PackageReference Include="CK.Ng.Zorro.BackOffice" Version="0.5.4--0006-develop" />
    </ItemGroup>
</Project>
