<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>True</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Ng.AspNet.Auth.Basic" Version="0.31.0" />
        <PackageReference Include="CK.Ng.Cris.AspNet.Auth" Version="0.55.0" />
        <PackageReference Include="CK.Ng.UserProfile.NamedUser" Version="0.6.1" />
        <PackageReference Include="CK.Ng.UserProfile.PreferredCulture" Version="0.6.1" />
        <PackageReference Include="CK.Ng.UserProfile.UserPassword" Version="0.6.1" />
        <PackageReference Include="CK.Ng.Zorro.BackOffice" Version="0.6.1" />
    </ItemGroup>
    
</Project>
